version: '3.8'

services:
  backend-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend-server
    command: sh -c "node Assignment\\ 3/backend/server.js"
    ports:
      - "5000:5000"
    working_dir: /app

  my:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my
    command: sh -c "npm start --prefix my"
    ports:
      - "3000:3000"
    working_dir: /app

  my-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-server
    command: sh -c "node my/src/components/Server.js"
    ports:
      - "5001:5001"
    working_dir: /app

  backend-db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend-db
    command: sh -c "node Assignment\\ 3/backend/db.js"
    working_dir: /app

  inventory-management:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: inventory-management
    command: sh -c "npm start --prefix Assignment\\ 3/inventory-management"
    ports:
      - "3006:3006"
    working_dir: /app

  proxy:
    image: caddy:2.3.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

